### ISSUE TITLE
Unable to resolve module dimensions?

### ISSUE THREAD

**Issue by ghost** [jmstout/react-native-viewport-units#4]
i am getting this error on the latest version of react native

"Unable to resolve module Dimensions from" then viewport-units.js

**Comment by ghost** [comment]
React Native 0.70+ introduced the need to use this instead

require('react-native').Dimensions

**Comment by jasecoop** [comment]
@jmstout This doesn't fix the issue for me, I still get this error on React-Native 0.14.2

![](https://s3.amazonaws.com/f.cl.ly/items/2m2H2N462X1t081S1V3l/Image%202015-11-18%20at%206.17.27%20pm.png)

**Comment by breadface** [comment]
I also get the same error

**Comment by altinselimi** [comment]
Me too. This should be fixed. (React v0.15)

**Comment by paintedbicycle** [comment]
This is fixed if you apply the patch in PR# https://github.com/jmstout/react-native-viewport-units/pull/5

**Comment by samkaraca** [comment]
Hi,

You can fix it by changing the following in viewport-unit.js:

from:
`var React = require('react-native')
  , Dimensions = React.Dimensions || require('Dimensions')
  , {width, height} = Dimensions.get('window');`
to
`var React = require('react-native');
var {
  Dimensions
} = React;
var {width, height} = Dimensions.get('window');`

after that restart packager

**Comment by abanobmikaeel** [comment]
Anything on this?

**Comment by zakaurehman** [comment]
i am getting this error on the latest version of react native

"Unable to resolve module Dimensions from" then viewport-units.j
